### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by 3runoDesign** [kevinkhill/FontAwesomePHP#11]
When trying to install the package, the following error occurred.
![screen shot 2016-04-08 at 2 15 48 am](https://cloud.githubusercontent.com/assets/1563041/14374752/ff2d1d42-fd2f-11e5-90f7-13e419450ed2.png)

**Comment by 3runoDesign** [comment]
What is the need to include?
https://github.com/kevinkhill/FontAwesomePHP/blob/1.0/src/FontAwesomeServiceProvider.php#L21

**Comment by kevinkhill** [comment]
I messed up and forgot to remove that line! I used to have a demo page but I removed it.

**Comment by kevinkhill** [comment]
Fix has been pushed, tagged [1.0.5](https://github.com/kevinkhill/FontAwesomePHP/releases/tag/1.0.5)
