### ISSUE TITLE
add an addAttr( attributeName, value ) method

### ISSUE THREAD

**Issue by lmj0011** [kevinkhill/FontAwesomePHP#12]
Being able to add attributes to an icon would come handy.
For example, those who would like to add a tooltip to an icon.

**Comment by kevinkhill** [comment]
That's a great idea! If you want to make a pull request, I'd happily merge it.

**Comment by lmj0011** [comment]
will take some time, but I'll look into it when I can.

**Comment by kevinkhill** [comment]
Included in the latest versions, so I'm closing this.
