### ISSUE TITLE
Not working on laravel 5.4

### ISSUE THREAD

**Issue by BadChoice** [kevinkhill/FontAwesomePHP#13]

**Comment by BadChoice** [comment]
Can you create a new version tag so we can update it?
Thanks!

**Comment by BadChoice** [comment]
Any news on the version update?

**Comment by kevinkhill** [comment]
Is composer not grabbing the tag? I created a [new tag](https://github.com/kevinkhill/FontAwesomePHP/releases/tag/1.1.1) with your pull request

**Comment by kevinkhill** [comment]
I don't know why Packagist didn't update, but I just forced an update so now [it shows v1.1.1](https://packagist.org/packages/khill/FontAwesomePHP)

**Comment by BadChoice** [comment]
Sorry but I found I forgot a `{` and the service provider was failing..
did another PR fixing that

I believe sublime played me a bad time with the copy/paste

Thnks!
BTW the 1.1.1 worked
