### ISSUE TITLE
spin

### ISSUE THREAD

**Issue by BadChoice** [kevinkhill/FontAwesomePHP#19]
I found that calling spin once, makes all icons spin, I can't find why.. or where does it, 

For example, if I call

```
{!! FA::spin('circle-o-notch'); !!}
```

Then all icons called by

```
{!! FA::icon('whatever`) !!}
```

Will spin too...

**Comment by kevinkhill** [comment]
Really? I have not encountered this. I will try it out and see whats up

**Comment by BadChoice** [comment]
Just tried in another project and works ok.. it might be something mine, let me investigate further..

**Comment by BadChoice** [comment]
Tried further, and yes, its happening, just to the calls done after you call the spin, put this in a view

```
    {!! FA::spin('circle-o-notch') !!}
    {!! FA::icon('circle-o-notch') !!}
    {!! FA::icon('truck') !!}
```

and you'll see all three icons spining

**Comment by BadChoice** [comment]
More info, if instead of using the facade, you use a `new FontAwesome('truck')` works so I guess it has something to do with the service provider/facade

**Comment by kevinkhill** [comment]
It must not be reseting the output buffer once spin is output to the page. The other calls must be inheriting the spin class.

**Comment by kevinkhill** [comment]
Making a new instance of the library is starting fresh, so that's why it works instead of getting the instance from the container

**Comment by kevinkhill** [comment]
I always forget to tag issues in my commits, but version 1.1.5 will fix the cascading spin icon bug.

**Comment by BadChoice** [comment]
Great thanks!
