### ISSUE TITLE
Feature request: get html entity of character

### ISSUE THREAD

**Issue by Rastishka** [kevinkhill/FontAwesomePHP#20]
Get html entity string like `&#xf00c;` or unicode character to use in selects, inputs etc.
```
<select value="somevalue" style="font-style: Arial,sans-serif,FontAwesome;">
    <option value=""></option>
    <option value="YES"><?= FA::htmlentity('check')?> yes</option>
    <option value="NO"><?= FA::htmlentity('times')?> no</option>
</select>
```
result like:
```
<select value="somevalue" style="font-style: Arial,sans-serif,FontAwesome;">
    <option value=""></option>
    <option value="YES">&#xf00c; yes</option>
    <option value="NO">&#xf00d; no</option>
</select>
```

**Comment by kevinkhill** [comment]
If there is an easy way to map the icon name to its corresponding entity, that would be do-able.

**Comment by drbyte** [comment]
That'd probably require mapping in almost the entire css file into a lookup array:
https://github.com/FortAwesome/Font-Awesome/blob/master/css/font-awesome.css#L183-L2318

And then maintain it during each release.

**Comment by kevinkhill** [comment]
Since I made this for a personal project and as a practice in creating a composer library, I don't really plan on maintaining it. I have too much going on to keep this up to date with font awesome. 

However, that being said, I will happily accept pull requests if you want to add features.
