### ISSUE TITLE
Add option for aliases?

### ISSUE THREAD

**Issue by robjbrain** [kevinkhill/FontAwesomePHP#22]
Would you consider adding the option for aliases, perhaps in a Laravel config file?

For instance you could do `icon('blog-post')` and alias "blog-post" to "edit".

A simple alias config could be:

```php
return [
    'blog-post' => 'edit',
    'category' => 'tag',
    'approve' => 'check'
];
```

That way you can use internal terminology and not have to remember which icon you're using for different areas of your site. Or if you want to change the icon for categories to "hashtag" instead of "tag" you can do it easily in one place.

**Comment by kevinkhill** [comment]
This.... I like this idea!

**Comment by kevinkhill** [comment]
I forgot `collections` was [already a feature I added](http://kevinkhill.github.io/FontAwesomePHP/#collection) :laughing: 

Would this achieve the same result you want?

**Comment by kevinkhill** [comment]
Closing this because I don't have to time to implement the feature and it is (sort of) possible already with collections
