### ISSUE TITLE
Ability to customize the location of the javascript

### ISSUE THREAD

**Issue by wesgro** [kevinkhill/FontAwesomePHP#24]
Would it be possible to customize where the FA assets gets loaded from?
LIke make https://github.com/kevinkhill/FontAwesomePHP/blob/3d04760bd7d71a69fc0dc0c3f509ba3ded6f5c4d/src/FontAwesome.php#L69 a property we can change when we invoke the class.

That way if we want to self-host the FA library we are able to, and not stuck with the FA CDN.

**Comment by kevinkhill** [comment]
This sounds like a good idea. While I carry my baby and answer this on my cell phone, I don't think I'll get a chance anytime soon.

XD

If you want to make this a feature, I'll be glad to accept a pull request

**Comment by kevinkhill** [comment]
You don't  have to use the provided `css()` or `js()` methods. You can add your own `script` and `link` tags to load the FA assets however you wish.
