### ISSUE TITLE
remove the route closure so we can route:cache 

### ISSUE THREAD

**Issue by BadChoice** [kevinkhill/FontAwesomePHP#7]
New laravel routes cache is not compatible for closure and there is the route included by default, 
can you remove it or use a controller?

**Comment by kevinkhill** [comment]
This was actually already fixed by @christianpv and I didn't realize that the pull request was still sitting there. My bad!

**Comment by BadChoice** [comment]
Great thank you!

On Fri, Oct 9, 2015 at 10:36 PM, Kevin Hill <notifications@github.com>
wrote:

> This was actually already fixed by @christianpv
> <https://github.com/christianpv> and I didn't realize that the pull
> request was still sitting there. My bad!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kevinkhill/FontAwesomePHP/issues/7#issuecomment-146980412>
> .
>



-- 

*Jordi* *Puigdellívol*
jordi@gloobus.net
